### ISSUE TITLE
Where do I get the Keycloak.json and what should it look like?

### ISSUE THREAD

**Issue by r-chris** [thedirtyfew/dash-keycloak#1]
I tried to export the .json config from Keycloak in the "Client" section, but that doesn't seem to be the right json config file. Do you know where I should be able to export that file from on my Keycloak server?

**Comment by emilhe** [comment]
Yes, it should be from the "Client" section. You should set the access type to "confidential" (under "Settings"), go to the "Installation" tab and select "Keycloak OIDC JSON". The format should be something like this,

```
{
  "realm": "my-realm",
  "auth-server-url": "https://keycloak.mydomain.net/auth/",
  "ssl-required": "none",
  "resource": "my-resource",
  "credentials": {
    "secret": "some-guid-like-thing"
  },
  "confidential-port": 0
}
```

**Comment by r-chris** [comment]
Thank - I'll try that. Btw - I found it very funny and coincidental that I stumbled across this repository of yours. After we recently discovered the amazingly useful `dash-leaflet`, I was actually just looking for a generic openid / oauth python lib, but ended up finding your Keycloak client :D

**Comment by r-chris** [comment]
I realized you actually included that piece of information in the README - I should have probably read that more carefully.
