### ISSUE TITLE
Make it possible to take the oicd json as dict or string, not only as file path 

### ISSUE THREAD

**Issue by sg-rs** [thedirtyfew/dash-keycloak#19]
In some cases there is no need or even no possibility to read/write files. In my case we are on a project on google cloud platform and we store our oicd json in an environment variable. We can't write it into a file because the google app engine restricts us writing to the file system. 

This could be easily avoided with just passing a string or a dict directly to the from_kc_oidc_json(...) function.

**Comment by emilhe** [comment]
The issue should be solved by the following PR,

https://github.com/thedirtyfew/dash-keycloak/pull/20

which has been merged and released as part of the 0.0.25 release.
